"""
Archive Models — Government Archive Platform

ArchiveLink: expirable links generated by approved citizens for INGRION.
IngrionKYCRequest: records of INGRION KYC submissions that reference this gov archive.
"""
import uuid
import secrets
from django.db import models
from django.utils import timezone
from gov_project.apps.accounts.models import CitizenUser


class ArchiveLink(models.Model):
    """
    One-time or expirable link generated by an approved citizen.
    INGRION uses this URL as the archive_link in KYC submission.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    citizen = models.ForeignKey(
        CitizenUser, on_delete=models.CASCADE, related_name='archive_links'
    )
    token = models.CharField(max_length=64, unique=True, db_index=True)

    # Configurable expiry
    expires_at = models.DateTimeField()
    is_revoked = models.BooleanField(default=False)

    # Tracks if INGRION has accessed this link
    accessed_at = models.DateTimeField(null=True, blank=True)
    access_count = models.PositiveIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = secrets.token_urlsafe(32)
        if not self.expires_at:
            from django.conf import settings
            self.expires_at = timezone.now() + timezone.timedelta(
                seconds=getattr(settings, 'ARCHIVE_LINK_EXPIRY_SECONDS', 86400)
            )
        super().save(*args, **kwargs)

    @property
    def is_expired(self):
        return timezone.now() > self.expires_at

    @property
    def is_valid(self):
        return not self.is_revoked and not self.is_expired

    def get_url(self, request=None):
        """Return the full public URL for this archive link."""
        base = 'http://localhost:8001'
        if request:
            base = request.build_absolute_uri('/').rstrip('/')
        return f'{base}/api/archive/verify/{self.token}/'

    def __str__(self):
        return f'ArchiveLink for {self.citizen.name} [{"valid" if self.is_valid else "expired"}]'


class IngrionKYCRequest(models.Model):
    """
    Records each time INGRION calls /api/archive/verify/<token>/
    with a KYC payload. Used for audit and to drive the callback.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    archive_link = models.ForeignKey(
        ArchiveLink, on_delete=models.SET_NULL, null=True, related_name='kyc_requests'
    )
    citizen = models.ForeignKey(
        CitizenUser, on_delete=models.SET_NULL, null=True, related_name='ingrion_requests'
    )

    # Data sent by INGRION
    ingrion_submission_id = models.CharField(max_length=64)
    public_key_b64 = models.CharField(max_length=128)
    facial_embedding_b64 = models.TextField()
    callback_url = models.URLField(max_length=2048)

    # Matching result
    facial_similarity = models.FloatField(null=True, blank=True)
    matched = models.BooleanField(default=False)

    # Status of this request
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('verified', 'Verified — callback sent'),
        ('rejected', 'Rejected — callback sent'),
        ('error', 'Error'),
    ]
    status = models.CharField(max_length=16, choices=STATUS_CHOICES, default='pending')
    callback_sent_at = models.DateTimeField(null=True, blank=True)
    source_ip = models.GenericIPAddressField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'INGRION request {self.ingrion_submission_id} [{self.status}]'
