# Generated by Django 5.0.6 on 2026-02-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kycsubmission',
            new_name='kyc_kycsubm_status_70a0c6_idx',
            old_name='kyc_submiss_status_idx',
        ),
        migrations.RenameIndex(
            model_name='kycsubmission',
            new_name='kyc_kycsubm_public__d21c16_idx',
            old_name='kyc_submiss_pub_key_idx',
        ),
    ]
