# Generated by Django 5.0.6 on 2026-02-24 19:34

import gov_project.apps.kyc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycdocument',
            name='file',
            field=models.FileField(upload_to=gov_project.apps.kyc.models.document_upload_path),
        ),
    ]
