# Generated by Django 5.0.6 on 2026-02-24 19:34

import gov_project.apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=gov_project.apps.accounts.models.profile_photo_path),
        ),
    ]
